FUSION_PATH = '/tmp/FUSION/'

INDEX_FRAME_BEGIN = 0
INDEX_MSG_TYPE = 1
INDEX_MSG_ID = 2
INDEX_NI = 3
INDEX_NMB_DATA = 4
INDEX_DATA = 5
FRAME_HEAD_LENGTH = 4
FRAME_CHECKSUM_LENGTH = 2
FRAME_BEGIN = 0xAA
MSG_TYPE_HANDSHAKE = 0
MSG_TYPE_LENGTH = 1
MSG_TYPE_PACKET = 2
WIFI_MODE_UDP = 1
WIFI_MODE_TCP = 2
